[colors]
[colors.primary]
background = "0x263137"
foreground = "0xeceef0"
[colors.cursor]
text = "0x000000"
cursor = "0xedeeed"
[colors.normal]
black = "0x546d79"
red = "0xff5151"
green = "0x69f0ad"
yellow = "0xffd73f"
blue = "0x40c4fe"
magenta = "0xff3f80"
cyan = "0x64fcda"
white = "0xfefefe"
[colors.bright]
black = "0xb0bec4"
red = "0xff8980"
green = "0xb9f6c9"
yellow = "0xffe47e"
blue = "0x80d7fe"
magenta = "0xff80ab"
cyan = "0xa7fdeb"
white = "0xfefefe"
